### ISSUE TITLE
Blank camera

### ISSUE THREAD

**Issue by alfaonyt** [SonySemiconductorSolutions/tof-ar-samples-ar#3]
Hi, when I try to use any ToF AR app sample from Sony (and the versions that I compile myself), I get a blank screen on my Xperia 1 IV running Android 13. The camera indicator says that it's in use when I select the camera or the ToF sensor but nothing shows in the app.

**Comment by HirotakaGoto** [comment]
Thank you for trying ToF AR application.

We built it according to the README, and it worked correctly on Xperia 1 IV running Android 13.
Additionally, we found that become blank screen when we imported ToF AR unity package for iOS intead of Android one.
Could you please check if you are importing the package correctly ?
We hope you can enjoy ToF AR applications.

ToF AR Team

**Comment by radoslawsz** [comment]
Maybe same problem like my (parsing 1.234 float numbers in country where 1,234 is valid format ):
change  all occurences float.Parse( .. ) in TofArTofManager.cs
to 
float.Parse( ... , System.Globalization.CultureInfo.InvariantCulture);

**Comment by HirotakaGoto** [comment]
Hello radoslawsz,

Thank you very much for your information !
We found the same problem when we also switched the region of the smartphone.
And we have confirmed that your changes fix the problem.
TofArTofManager.cs is included in the ToF AR SDK, so we will try to release a fixed version.
We apologize that the release of new ToF AR SDK will take time.

ToF AR Team

**Comment by tofar-integ01** [comment]
Hello alfaonyt and radoslawsz,

We released the fixed ToF AR v1.3.1 and Apps on May 29th.
Make sure to keep your ToF AR toolkit up to date!

ToF AR Team
