### ISSUE TITLE
Low level API ? 

### ISSUE THREAD

**Issue by cclaan** [SonySemiconductorSolutions/tof-ar-samples-ar#4]
Hi, is there a C++ version of the library planned ( for just core features like depth access ) ? 
Thanks

**Comment by tofar-integ01** [comment]
Thank you for your interest in ToF AR.

Unfortunately, we are not planning to release the C++ version of the library.

ToF AR team

**Comment by cclaan** [comment]
Thanks for the reply. Can you recommend any resources for accessing the ToF data without using Unity?

**Comment by tofar-integ01** [comment]
Thank you for your comment.

ToF AR cannot access to the depth data without using Unity.
We recommend ARKit for iOS and ARCore for Android if you want to direct access to the depth data without using ToF AR.
Please refer to the manual below.
ArKit: https://developer.apple.com/documentation/arkit/arkit_in_ios/environmental_analysis/displaying_a_point_cloud_using_scene_depth
ARCore: https://codelabs.developers.google.com/codelabs/arcore-depth

ToF AR Team
